### ISSUE TITLE
Is the update also guaranteed?

### ISSUE THREAD

**Issue by caiosweet** [0limits91/dpc-allerta-meteo#1]
Hi, thanks for the contribution. 
I'm **NOT a developer** and I haven't tried it yet, also because I had to choose another way (to integrate dpc into the Home Assistant) ... but, with a quick look, if there was an update, (look at the [files](https://github.com/pcm-dpc/DPC-Bollettini-Criticita-Idrogeologica-Idraulica/tree/master/files/all) with date 20210803_1524_all.zip and 20210803_1743_all.zip) maybe you should get the last file, or am I wrong? Because [here](https://github.com/0limits91/dpc-allerta-meteo/blob/90b12fc1f948284e509b445a60764ba4584df325/v2/dpcBollettiniRepositoryParser.py#L41), it seems that it stops at the first one it finds.

In any case, I believe I will learn a lot from your code, thanks for sharing your work !!!

**Comment by 0limits91** [comment]
Hi,
I assumed that there was a single daily report. I updated by taking the latest uploaded report.
Best Regards, 
Francesco

**Comment by caiosweet** [comment]
Well, and thanks again for sharing. Good job. :0)
